import { useMemo, useState, type ReactNode } from 'react';
import { Box, Button, Slider, TextField, Typography } from '@mui/material';
import type { Locale, WidgetDefinition, WidgetSize, WidgetThemeTokens } from '../core/types';
import { bars, heat, spark, spark2 } from '../data/mockData';
interface Props {
    def: WidgetDefinition;
    theme: WidgetThemeTokens;
    locale: Locale;
    size: WidgetSize;
}
type TableMode = 'table' | 'measurement-list' | 'alarms' | 'events' | 'logs';
const n = (v: unknown, f = 0) => typeof v === 'number' ? v : f;
const s = (v: unknown, f = '') => typeof v === 'string' ? v : f;
const clamp = (v: number, min: number, max: number) => Math.min(max, Math.max(min, v));
const tr = (locale: Locale, en: string, fa: string) => locale === 'fa' ? fa : en;
function profile(size: WidgetSize) {
    const [w, h] = size.split('x').map(Number);
    const area = w * h;
    return { w, h, area, compact: area === 1, wide: w > h, tall: h > w, large: area >= 4, veryWide: w >= 3, veryTall: h >= 3, rich: area >= 4 || w >= 3 || h >= 2 };
}
const C = { success: '#5eead4', warning: '#fbbf24', danger: '#fb7185', blue: '#7dd3fc', violet: '#c4b5fd', muted: 'rgba(226,241,247,.68)', faint: 'rgba(226,241,247,.46)' };
function GlassPlate({ children, accent = false, sx = {} }: {
    children: ReactNode;
    accent?: boolean;
    sx?: Record<string, any>;
}) {
    return <Box sx={{ borderRadius: '12px', border: `1px solid ${accent ? 'rgba(125,211,252,.22)' : 'rgba(214,246,255,.09)'}`, background: accent ? 'linear-gradient(145deg,rgba(125,211,252,.095),rgba(5,27,40,.34))' : 'linear-gradient(145deg,rgba(255,255,255,.035),rgba(3,18,31,.30))', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.045), inset 0 -1px 0 rgba(125,211,252,.025)', ...sx }}>{children}</Box>;
}
function MiniStat({ label, value, accent = false }: {
    label: string;
    value: string;
    accent?: boolean;
}) {
    return <GlassPlate accent={accent} sx={{ p: .8, minWidth: 0 }}><Typography sx={{ fontSize: 8.8, letterSpacing: .55, textTransform: 'uppercase', color: C.faint, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{label}</Typography><Typography sx={{ mt: .25, fontSize: 12.2, fontWeight: 800, color: accent ? C.blue : '#f7fbff', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', direction: 'ltr' }}>{value}</Typography></GlassPlate>;
}
function StatusText({ children, color = C.success }: {
    children: ReactNode;
    color?: string;
}) {
    return <Box sx={{ display: 'inline-flex', alignItems: 'center', gap: .55 }}><Box sx={{ width: 5, height: 5, borderRadius: '50%', bgcolor: color, boxShadow: `0 0 10px ${color}99` }}/><Typography sx={{ fontSize: 9.7, fontWeight: 760, color }}>{children}</Typography></Box>;
}
function trace(values: number[]) {
    const min = Math.min(...values), max = Math.max(...values), range = Math.max(1, max - min);
    return values.map((v, i) => `${(i / Math.max(1, values.length - 1)) * 100},${38 - ((v - min) / range) * 30}`).join(' ');
}
function LuminousChart({ values = spark, color = C.blue, fill = false, height = '100%', dots = false }: {
    values?: number[];
    color?: string;
    fill?: boolean;
    height?: number | string;
    dots?: boolean;
}) {
    const points = useMemo(() => trace(values), [values]);
    return <Box sx={{ width: '100%', height, minHeight: 0, position: 'relative', overflow: 'hidden' }}>
    <svg viewBox="0 0 100 42" preserveAspectRatio="none" width="100%" height="100%" aria-hidden>
      {[9, 20, 31].map(y => <line key={y} x1="0" x2="100" y1={y} y2={y} stroke="rgba(255,255,255,.075)" strokeWidth=".35"/>)}
      {[20, 40, 60, 80].map(x => <line key={x} y1="3" y2="39" x1={x} x2={x} stroke="rgba(255,255,255,.045)" strokeWidth=".3"/>)}
      <defs><linearGradient id={`area-${color.replace(/[^a-z0-9]/gi, '')}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".28"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs>
      {fill && <polygon points={`0,42 ${points} 100,42`} fill={`url(#area-${color.replace(/[^a-z0-9]/gi, '')})`}/>} 
      <polyline points={points} fill="none" stroke={color} strokeWidth="1.8" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/>
      {dots && values.map((_, i) => i % 3 === 0 ? <circle key={i} cx={(i / Math.max(1, values.length - 1)) * 100} cy={Number(points.split(' ')[i]?.split(',')[1] ?? 20)} r="1.3" fill={color}/> : null)}
    </svg>
  </Box>;
}
function ScaleBar({ value, max = 100, color = C.blue }: {
    value: number;
    max?: number;
    color?: string;
}) {
    const pct = clamp(value / Math.max(1, max) * 100, 0, 100);
    return <Box sx={{ height: 6, borderRadius: 3, bgcolor: 'rgba(255,255,255,.08)', overflow: 'hidden', position: 'relative' }}><Box sx={{ height: '100%', width: `${pct}%`, background: `linear-gradient(90deg,${color},${C.violet})`, boxShadow: `0 0 14px ${color}66` }}/></Box>;
}
function GlassMetric({ def, theme, locale, size }: Props) {
    const p = profile(size), value = n(def.mock.value, 24.8), unit = s(def.mock.unit), trend = n(def.mock.trend, 2.4), values = (def.mock.values as number[] | undefined) ?? spark, max = n(def.mock.max, Math.max(100, value * 1.35));
    const positive = trend >= 0, trendColor = positive ? C.success : C.warning;
    if (p.compact)
        return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto auto minmax(0,1fr)', gap: .7, direction: 'ltr' }}>
    <Box><Typography sx={{ fontSize: 36, fontWeight: 760, lineHeight: .9, letterSpacing: '-.055em', textShadow: '0 8px 26px rgba(0,0,0,.18)' }}>{value}<Box component="span" sx={{ fontSize: 12, ml: .55, color: C.muted, fontWeight: 650 }}>{unit}</Box></Typography></Box>
    <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: .8 }}><StatusText color={trendColor}>{positive ? '↑' : '↓'} {Math.abs(trend)}% · 24h</StatusText><Typography sx={{ fontSize: 8.8, color: C.faint }}>LIVE</Typography></Box>
    <Box sx={{ minHeight: 0, borderTop: '1px solid rgba(255,255,255,.09)', pt: .45 }}><LuminousChart values={values} color={theme.accent} fill/></Box>
  </Box>;
    if (p.wide && !p.large)
        return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: 'minmax(126px,.8fr) minmax(0,1.4fr)', gap: 1.25, direction: 'ltr' }}>
    <Box sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', minWidth: 0 }}><Typography sx={{ fontSize: 40, fontWeight: 760, lineHeight: .9, letterSpacing: '-.055em' }}>{value}<Box component="span" sx={{ fontSize: 13, ml: .55, color: C.muted }}>{unit}</Box></Typography><Box sx={{ mt: 1 }}><StatusText color={trendColor}>{positive ? '↑' : '↓'} {Math.abs(trend)}% / 24h</StatusText></Box><Box sx={{ mt: 1.15 }}><ScaleBar value={value} max={max} color={theme.accent}/></Box></Box>
    <GlassPlate sx={{ p: .8, minWidth: 0, display: 'grid', gridTemplateRows: 'auto minmax(0,1fr)' }}><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: 9, color: C.faint }}>{tr(locale, '24h trace', 'روند ۲۴ ساعت')}</Typography><Typography sx={{ fontSize: 9, color: C.faint }}>MIN {Math.round(value * .87)} · MAX {Math.round(value * 1.11)}</Typography></Box><LuminousChart values={values} color={theme.accent} fill/></GlassPlate>
  </Box>;
    if (p.tall && !p.large)
        return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto minmax(90px,1fr) auto', gap: 1, direction: 'ltr' }}><Box><Typography sx={{ fontSize: 42, fontWeight: 760, lineHeight: .9 }}>{value}<Box component="span" sx={{ fontSize: 13, ml: .55, color: C.muted }}>{unit}</Box></Typography><Box sx={{ mt: .8 }}><StatusText color={trendColor}>{positive ? '↑' : '↓'} {Math.abs(trend)}% / 24h</StatusText></Box></Box><GlassPlate sx={{ p: .7, minHeight: 0 }}><LuminousChart values={values} color={theme.accent} fill dots/></GlassPlate><Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: .7 }}><MiniStat label={tr(locale, 'Low', 'کمینه')} value={`${Math.round(value * .87)} ${unit}`}/><MiniStat label={tr(locale, 'High', 'بیشینه')} value={`${Math.round(value * 1.11)} ${unit}`} accent/></Box></Box>;
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto auto minmax(0,1fr)', gap: 1, direction: 'ltr' }}><Box sx={{ display: 'flex', alignItems: 'end', justifyContent: 'space-between', gap: 1 }}><Box><Typography sx={{ fontSize: 46, fontWeight: 760, lineHeight: .86, letterSpacing: '-.06em' }}>{value}<Box component="span" sx={{ fontSize: 14, ml: .6, color: C.muted }}>{unit}</Box></Typography><Box sx={{ mt: .8 }}><StatusText color={trendColor}>{positive ? '↑' : '↓'} {Math.abs(trend)}% / 24h</StatusText></Box></Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(70px,1fr))', gap: .65, maxWidth: 300 }}><MiniStat label="MIN" value={`${Math.round(value * .87)} ${unit}`}/><MiniStat label="AVG" value={`${value} ${unit}`} accent/><MiniStat label="MAX" value={`${Math.round(value * 1.11)} ${unit}`}/></Box></Box><ScaleBar value={value} max={max} color={theme.accent}/><GlassPlate sx={{ p: .8, minHeight: 0 }}><LuminousChart values={values} color={theme.accent} fill dots/></GlassPlate></Box>;
}
function BatteryShape({ value, vertical = false }: {
    value: number;
    vertical?: boolean;
}) {
    const level = value < 20 ? C.danger : value < 45 ? C.warning : C.success;
    if (vertical)
        return <Box sx={{ width: 70, height: 128, border: '1.5px solid rgba(255,255,255,.34)', borderRadius: '16px', p: .6, position: 'relative', display: 'flex', alignItems: 'end', '&:before': { content: '""', position: 'absolute', top: -7, left: '36%', width: '28%', height: 6, borderRadius: '3px 3px 0 0', bgcolor: 'rgba(255,255,255,.34)' } }}><Box sx={{ width: '100%', height: `${value}%`, borderRadius: '10px', background: `linear-gradient(180deg,${level},${C.blue})`, boxShadow: `0 0 22px ${level}55`, position: 'relative', '&:after': { content: '""', position: 'absolute', left: 6, right: 6, top: 5, height: 1, bgcolor: 'rgba(255,255,255,.55)' } }}/></Box>;
    return <Box sx={{ width: 118, height: 54, border: '1.5px solid rgba(255,255,255,.34)', borderRadius: '15px', p: .55, position: 'relative', '&:after': { content: '""', position: 'absolute', right: -6, top: '31%', width: 5, height: '38%', borderRadius: '0 3px 3px 0', bgcolor: 'rgba(255,255,255,.34)' } }}><Box sx={{ height: '100%', width: `${value}%`, borderRadius: '10px', background: `linear-gradient(90deg,${C.blue},${level})`, boxShadow: `0 0 22px ${level}55` }}/></Box>;
}
function GlassBattery({ def, locale, size }: Props) {
    const p = profile(size), value = clamp(n(def.mock.value, 76), 0, 100), voltage = s(def.mock.voltage, '3.94 V'), remain = s(def.mock.remaining, '8h 42m');
    if (p.compact)
        return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', direction: 'ltr' }}><Box sx={{ textAlign: 'center' }}><BatteryShape value={value}/><Typography sx={{ mt: .8, fontSize: 25, fontWeight: 800 }}>{value}%</Typography></Box></Box>;
    if (p.tall && !p.large)
        return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: '1fr auto', placeItems: 'center', gap: 1, direction: 'ltr' }}><Box sx={{ display: 'grid', placeItems: 'center' }}><BatteryShape value={value} vertical/></Box><Box sx={{ width: '100%', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: .7 }}><MiniStat label="VOLTAGE" value={voltage}/><MiniStat label={tr(locale, 'ETA', 'باقی‌مانده')} value={remain} accent/></Box></Box>;
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: p.large ? 'auto auto 1fr' : '1fr', gap: 1, direction: 'ltr' }}><Box sx={{ display: 'grid', gridTemplateColumns: 'auto 1fr', alignItems: 'center', gap: 1.5 }}><BatteryShape value={value}/><Box><Typography sx={{ fontSize: p.large ? 38 : 34, fontWeight: 800, lineHeight: .9 }}>{value}%</Typography><StatusText>{tr(locale, 'Healthy discharge', 'دشارژ عادی')}</StatusText></Box></Box>{p.large && <><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label="VOLTAGE" value={voltage}/><MiniStat label={tr(locale, 'ETA', 'باقی‌مانده')} value={remain} accent/><MiniStat label={tr(locale, 'Cycles', 'چرخه‌ها')} value="184"/></Box><GlassPlate sx={{ p: .8, minHeight: 0 }}><LuminousChart values={[96, 93, 90, 88, 85, 82, 80, 78, 77, 76]} color={C.success} fill/></GlassPlate></>}</Box>;
}
function SignalBars({ strength = 4, big = false }: {
    strength?: number;
    big?: boolean;
}) { return <Box sx={{ display: 'flex', alignItems: 'end', gap: big ? .7 : .5, height: big ? 82 : 58 }}>{[1, 2, 3, 4, 5].map(i => <Box key={i} sx={{ width: big ? 13 : 10, height: (big ? 11 : 8) + i * (big ? 12 : 9), borderRadius: '4px 4px 2px 2px', background: i <= strength ? `linear-gradient(180deg,${C.blue},${C.success})` : 'rgba(255,255,255,.09)', boxShadow: i <= strength ? `0 0 16px ${C.blue}44` : 'none' }}/>)}</Box>; }
function GlassSignal({ def, locale, size }: Props) {
    const p = profile(size), value = n(def.mock.value, -72), strength = value > -60 ? 5 : value > -70 ? 4 : value > -80 ? 3 : value > -90 ? 2 : 1, network = s(def.mock.network, 'LTE · RSRP');
    if (p.compact)
        return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', textAlign: 'center', direction: 'ltr' }}><Box><SignalBars strength={strength}/><Typography sx={{ mt: .8, fontSize: 22, fontWeight: 820 }}>{value} <Box component="span" sx={{ fontSize: 10, color: C.muted }}>dBm</Box></Typography></Box></Box>;
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: p.wide && !p.large ? 'auto 1fr' : '1fr', gridTemplateRows: p.wide && !p.large ? '1fr' : p.large ? 'auto auto minmax(0,1fr)' : 'auto 1fr', gap: 1.1, direction: 'ltr', alignItems: 'center' }}><Box sx={{ display: 'flex', alignItems: 'center', gap: 1.3 }}><SignalBars strength={strength} big={p.large}/><Box><Typography sx={{ fontSize: p.large ? 34 : 30, fontWeight: 820 }}>{value} <Box component="span" sx={{ fontSize: 11, color: C.muted }}>dBm</Box></Typography><StatusText>{network}</StatusText></Box></Box>{p.wide && !p.large ? <GlassPlate sx={{ p: .8, height: '100%', minHeight: 0 }}><LuminousChart values={[-81, -78, -76, -74, -75, -71, -72, -69, -72]} color={C.blue} fill/></GlassPlate> : <><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label="RSRQ" value="-9 dB"/><MiniStat label="SINR" value="18 dB" accent/><MiniStat label={tr(locale, 'Cell', 'سلول')} value="LTE B3"/></Box>{p.large && <GlassPlate sx={{ p: .8, minHeight: 0 }}><LuminousChart values={[-84, -81, -79, -75, -73, -72, -70, -73, -72, -71, -72]} color={C.blue} fill/></GlassPlate>}</>}</Box>;
}
function TankGraphic({ value, tall = false }: {
    value: number;
    tall?: boolean;
}) { const h = tall ? 160 : 116, w = tall ? 92 : 80; return <Box sx={{ width: w, height: h, border: '1.5px solid rgba(255,255,255,.27)', borderRadius: '18px 18px 24px 24px', p: .65, display: 'flex', alignItems: 'end', position: 'relative', overflow: 'hidden', background: 'linear-gradient(180deg,rgba(255,255,255,.06),rgba(255,255,255,.015))', '&:before': { content: '""', position: 'absolute', left: '18%', right: '18%', top: 10, height: 1, bgcolor: 'rgba(255,255,255,.18)' } }}><Box sx={{ height: `${value}%`, width: '100%', borderRadius: '11px 11px 18px 18px', background: `linear-gradient(180deg,${C.blue}cc,#22d3ee99)`, boxShadow: `0 0 28px ${C.blue}44`, position: 'relative', '&:before': { content: '""', position: 'absolute', left: -2, right: -2, top: -5, height: 10, borderRadius: '50%', background: 'rgba(186,230,253,.85)', boxShadow: '0 0 16px rgba(125,211,252,.6)' } }}/><Box sx={{ position: 'absolute', inset: 0, background: 'linear-gradient(105deg,rgba(255,255,255,.11),transparent 25%)' }}/></Box>; }
function GlassTank({ def, locale, size }: Props) {
    const p = profile(size), value = clamp(n(def.mock.value, 63), 0, 100), liters = s(def.mock.liters, `${Math.round(value * 20)} L`);
    if (p.compact)
        return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: 'auto 1fr', alignItems: 'center', gap: 1.1, direction: 'ltr' }}><TankGraphic value={value}/><Box><Typography sx={{ fontSize: 31, fontWeight: 820, lineHeight: .9 }}>{value}%</Typography><Typography sx={{ mt: .5, fontSize: 10, color: C.muted }}>{liters}</Typography></Box></Box>;
    if (p.tall && !p.large)
        return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: '1fr auto', placeItems: 'center', gap: 1, direction: 'ltr' }}><TankGraphic value={value} tall/><Box sx={{ width: '100%' }}><Typography sx={{ fontSize: 31, fontWeight: 820, textAlign: 'center' }}>{value}%</Typography><Box sx={{ mt: .6, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: .7 }}><MiniStat label={tr(locale, 'Volume', 'حجم')} value={liters} accent/><MiniStat label={tr(locale, 'State', 'وضعیت')} value={tr(locale, 'Stable', 'پایدار')}/></Box></Box></Box>;
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: 'auto 1fr', gap: 1.4, direction: 'ltr', alignItems: 'center' }}><TankGraphic value={value} tall={p.large}/><Box sx={{ minWidth: 0 }}><Typography sx={{ fontSize: p.large ? 42 : 36, fontWeight: 820, lineHeight: .88 }}>{value}%</Typography><Typography sx={{ mt: .5, fontSize: 11, color: C.muted }}>{liters} · {tr(locale, 'available', 'موجود')}</Typography><Box sx={{ mt: 1.1 }}><ScaleBar value={value} color={C.blue}/></Box>{p.large && <><Box sx={{ mt: 1, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: .7 }}><MiniStat label={tr(locale, 'Fill rate', 'نرخ ورودی')} value="+18 L/min" accent/><MiniStat label={tr(locale, 'Est. full', 'تا پر شدن')} value="42 min"/></Box><Box sx={{ mt: 1, height: 72 }}><LuminousChart values={[49, 51, 53, 54, 56, 58, 59, 61, 62, 63]} color={C.blue} fill/></Box></>}</Box></Box>;
}
function GlassBoolean({ def, locale, size }: Props) {
    const p = profile(size), [on, setOn] = useState(Boolean(def.mock.value)), isLock = def.id === 'door-lock', isSiren = def.id === 'siren';
    const label = on ? (isLock ? tr(locale, 'Locked', 'قفل') : isSiren ? tr(locale, 'Active', 'فعال') : tr(locale, 'Online', 'آنلاین')) : (isLock ? tr(locale, 'Unlocked', 'باز') : isSiren ? tr(locale, 'Standby', 'آماده') : tr(locale, 'Offline', 'آفلاین'));
    const color = on ? C.success : 'rgba(226,241,247,.42)';
    const indicator = <Box onClick={() => setOn(v => !v)} sx={{ cursor: 'pointer', textAlign: 'center', userSelect: 'none' }}><Box sx={{ width: p.large ? 142 : p.compact ? 78 : 90, height: p.large ? 142 : p.compact ? 78 : 90, borderRadius: '50%', mx: 'auto', display: 'grid', placeItems: 'center', position: 'relative', background: on ? `radial-gradient(circle at 35% 28%,rgba(255,255,255,.22),${color}24 34%,rgba(4,22,34,.40) 72%)` : 'radial-gradient(circle at 35% 28%,rgba(255,255,255,.08),rgba(4,22,34,.40) 68%)', border: `1px solid ${on ? `${color}55` : 'rgba(255,255,255,.12)'}`, boxShadow: on ? `0 0 28px ${color}22, inset 0 0 24px ${color}0f` : 'inset 0 0 20px rgba(255,255,255,.02)' }}><Box sx={{ position: 'absolute', inset: p.large ? 15 : 10, borderRadius: '50%', border: `1px solid ${on ? `${color}28` : 'rgba(255,255,255,.06)'}` }}/><Box sx={{ width: p.large ? 29 : 19, height: p.large ? 29 : 19, borderRadius: '50%', bgcolor: color, boxShadow: on ? `0 0 18px ${color}` : 'none' }}/></Box><Typography sx={{ mt: .8, fontSize: p.compact ? 13 : p.large ? 19 : 16, fontWeight: 820, color: on ? '#f8ffff' : C.muted }}>{label}</Typography></Box>;
    if (!p.large) return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', direction: 'ltr' }}>{indicator}</Box>;
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'minmax(0,1fr) auto', gap: 1, direction: 'ltr' }}><Box sx={{ display: 'grid', gridTemplateColumns: 'minmax(150px,.82fr) minmax(0,1.18fr)', alignItems: 'center', gap: 1.2 }}><Box sx={{ display: 'grid', placeItems: 'center' }}>{indicator}</Box><GlassPlate sx={{ p: 1.05, display: 'grid', alignContent: 'center', gap: .9 }}><StatusText color={color}>{on ? tr(locale, 'Telemetry heartbeat received', 'ضربان تله‌متری دریافت شد') : tr(locale, 'No recent heartbeat', 'ضربان جدید دریافت نشده')}</StatusText><Box sx={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: .8, alignItems: 'center' }}><Typography sx={{ fontSize: 10, color: C.muted }}>{tr(locale, 'Availability', 'دسترس‌پذیری')}</Typography><Typography sx={{ fontSize: 13, fontWeight: 820 }}>99.98%</Typography><Typography sx={{ fontSize: 10, color: C.muted }}>{tr(locale, 'Round trip', 'رفت‌وبرگشت')}</Typography><Typography sx={{ fontSize: 13, fontWeight: 820, color: C.blue }}>18 ms</Typography><Typography sx={{ fontSize: 10, color: C.muted }}>{tr(locale, 'Uptime', 'زمان کار')}</Typography><Typography sx={{ fontSize: 13, fontWeight: 820 }}>12d 7h</Typography></Box></GlassPlate></Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label={tr(locale, 'Last change', 'آخرین تغییر')} value="09:42"/><MiniStat label={tr(locale, 'Source', 'منبع')} value="Dashboard"/><MiniStat label={tr(locale, 'State', 'وضعیت')} value={on ? 'ON' : 'OFF'} accent/></Box></Box>;
}
function GlassAlarm({ def, locale, size }: Props) {
    const p = profile(size), Icon = def.icon, active = Boolean(def.mock.value), severity = s(def.mock.severity, 'warning'), color = active ? (severity === 'critical' ? C.danger : C.warning) : C.success, label = active ? tr(locale, 'ALARM ACTIVE', 'هشدار فعال') : tr(locale, 'NORMAL', 'عادی');
    const badge = <Box sx={{ width: p.large ? 150 : p.compact ? 78 : 94, height: p.large ? 150 : p.compact ? 78 : 94, mx: 'auto', position: 'relative', display: 'grid', placeItems: 'center', clipPath: 'polygon(50% 0,92% 24%,100% 68%,72% 100%,28% 100%,0 68%,8% 24%)', background: `radial-gradient(circle at 38% 28%,${color}2c,${color}0d 48%,rgba(4,22,34,.36) 72%)`, border: `1px solid ${color}3d`, boxShadow: active ? `0 0 32px ${color}26` : 'inset 0 0 28px rgba(255,255,255,.025)' }}><Box sx={{ position: 'absolute', inset: p.large ? 20 : 13, clipPath: 'inherit', border: `1px solid ${color}24` }}/><Icon sx={{ fontSize: p.large ? 68 : p.compact ? 34 : 42, color, filter: `drop-shadow(0 0 8px ${color}44)` }}/></Box>;
    if (!p.large) return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center' }}><Box sx={{ textAlign: 'center' }}>{badge}<Typography sx={{ mt: .7, fontSize: p.compact ? 11 : 13, fontWeight: 850, letterSpacing: .7, color }}>{label}</Typography><Typography sx={{ mt: .2, fontSize: 9.5, color: C.muted }}>{active ? tr(locale, 'Immediate attention', 'نیازمند بررسی') : tr(locale, 'Sensor armed', 'سنسور آماده')}</Typography></Box></Box>;
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'minmax(0,1fr) auto', gap: 1 }}><Box sx={{ minHeight: 0, display: 'grid', gridTemplateColumns: '170px minmax(0,1fr)', alignItems: 'center', gap: 1.25, direction: locale === 'fa' ? 'rtl' : 'ltr' }}><Box sx={{ display: 'grid', placeItems: 'center' }}>{badge}</Box><Box sx={{ minWidth: 0 }}><Typography sx={{ fontSize: 23, lineHeight: 1, fontWeight: 860, letterSpacing: .4, color }}>{label}</Typography><Typography sx={{ mt: .55, fontSize: 10.5, color: C.muted }}>{active ? tr(locale, 'Immediate attention required. Alarm loop is reporting an active condition.', 'نیازمند بررسی فوری. حلقه هشدار وضعیت فعال گزارش می‌کند.') : tr(locale, 'Sensor loop is armed and reporting normally.', 'حلقه سنسور فعال است و وضعیت عادی گزارش می‌کند.')}</Typography><GlassPlate sx={{ mt: 1, p: .85, display: 'grid', gridTemplateColumns: '1fr auto', gap: .75, alignItems: 'center', direction: 'ltr' }}><Typography sx={{ fontSize: 9.5, color: C.muted }}>LOOP / CHANNEL</Typography><Typography sx={{ fontSize: 11.5, fontWeight: 800 }}>CH-02</Typography><Typography sx={{ fontSize: 9.5, color: C.muted }}>LAST EVENT</Typography><Typography sx={{ fontSize: 11.5, fontWeight: 800, color }}>09:41:18</Typography><Typography sx={{ fontSize: 9.5, color: C.muted }}>ACK</Typography><Typography sx={{ fontSize: 11.5, fontWeight: 800 }}>{active ? 'PENDING' : 'CLEAR'}</Typography></GlassPlate></Box></Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label={tr(locale, 'Zone', 'ناحیه')} value="ZONE 02"/><MiniStat label={tr(locale, 'Last test', 'آخرین تست')} value="08:15"/><MiniStat label={tr(locale, 'State', 'وضعیت')} value={active ? 'ACTIVE' : 'ARMED'} accent/></Box></Box>;
}
function RadialGauge({ id, value, max, unit, size, color }: {
    id: string;
    value: number;
    max: number;
    unit: string;
    size: number;
    color: string;
}) { const pct = clamp(value / Math.max(1, max), 0, 1), r = 44, c = 2 * Math.PI * r, arc = c * .72; return <Box sx={{ position: 'relative', width: size, height: size }}><svg viewBox="0 0 120 120" width="100%" height="100%"><defs><linearGradient id={`gauge-${id.replace(/[^a-z0-9_-]/gi, '')}`} x1="0" x2="1"><stop offset="0" stopColor={C.blue}/><stop offset="1" stopColor={color}/></linearGradient></defs><circle cx="60" cy="62" r={r} fill="rgba(255,255,255,.025)" stroke="rgba(255,255,255,.085)" strokeWidth="10" strokeLinecap="round" strokeDasharray={`${arc} ${c}`} transform="rotate(140 60 62)"/><circle cx="60" cy="62" r={r} fill="none" stroke={`url(#gauge-${id.replace(/[^a-z0-9_-]/gi, '')})`} strokeWidth="10" strokeLinecap="round" strokeDasharray={`${arc * pct} ${c}`} transform="rotate(140 60 62)"/>{[0, .25, .5, .75, 1].map((t, i) => { const a = (140 + 260 * t) * Math.PI / 180, x1 = 60 + 34 * Math.cos(a), y1 = 62 + 34 * Math.sin(a), x2 = 60 + 38 * Math.cos(a), y2 = 62 + 38 * Math.sin(a); return <line key={i} x1={x1} y1={y1} x2={x2} y2={y2} stroke="rgba(255,255,255,.32)" strokeWidth="1"/>; })}</svg><Box sx={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', textAlign: 'center', pt: 1 }}><Box><Typography sx={{ fontSize: size > 160 ? 31 : 26, fontWeight: 820, lineHeight: .95 }}>{value}</Typography><Typography sx={{ mt: .25, fontSize: 9.5, color: C.muted }}>{unit}</Typography></Box></Box></Box>; }
function GlassGauge({ def, locale, size }: Props) {
    const p = profile(size), value = n(def.mock.value, 68), max = n(def.mock.max, 100), unit = s(def.mock.unit), pct = value / Math.max(1, max), color = pct > .9 ? C.danger : pct > .78 ? C.warning : C.success;
    if (p.compact)
        return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center' }}><RadialGauge id={def.id} value={value} max={max} unit={unit} size={126} color={color}/></Box>;
    if (p.wide && !p.large)
        return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: '150px 1fr', alignItems: 'center', gap: 1.2, direction: 'ltr' }}><RadialGauge id={def.id} value={value} max={max} unit={unit} size={146} color={color}/><Box><Typography sx={{ fontSize: 11, color: C.muted }}>{tr(locale, 'Operating window', 'محدوده کاری')}</Typography><Box sx={{ mt: .8 }}><ScaleBar value={value} max={max} color={color}/></Box><Box sx={{ mt: 1, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: .7 }}><MiniStat label={tr(locale, 'Limit', 'حد')} value={`${max} ${unit}`}/><MiniStat label={tr(locale, 'Load', 'بار')} value={`${Math.round(pct * 100)}%`} accent/></Box></Box></Box>;
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: p.tall && !p.large ? '1fr' : 'minmax(160px,.8fr) 1fr', gridTemplateRows: p.tall && !p.large ? 'auto 1fr' : '1fr', gap: 1.2, direction: 'ltr', alignItems: 'center' }}><Box sx={{ display: 'grid', placeItems: 'center' }}><RadialGauge id={def.id} value={value} max={max} unit={unit} size={p.large ? 188 : 156} color={color}/></Box><Box sx={{ width: '100%', alignSelf: 'stretch', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}><StatusText color={color}>{pct > .9 ? tr(locale, 'Critical range', 'محدوده بحرانی') : pct > .78 ? tr(locale, 'Near limit', 'نزدیک حد') : tr(locale, 'Within range', 'در محدوده')}</StatusText><Box sx={{ mt: 1, display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label="MIN" value="0"/><MiniStat label={tr(locale, 'Current', 'فعلی')} value={`${value} ${unit}`} accent/><MiniStat label="MAX" value={`${max}`}/></Box>{p.large && <GlassPlate sx={{ mt: 1, p: .7, flex: 1, minHeight: 70 }}><LuminousChart values={[44, 49, 48, 55, 61, 59, 64, 68, 66, 68]} color={color} fill/></GlassPlate>}</Box></Box>;
}
function ChartHeader({ summary, locale }: {
    summary: string;
    locale: Locale;
}) { return <Box sx={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 1, direction: 'ltr' }}><Typography sx={{ fontSize: 24, fontWeight: 820, letterSpacing: '-.025em' }}>{summary}</Typography><Typography sx={{ fontSize: 9.5, color: C.faint }}>{tr(locale, 'LAST 24H', '۲۴ ساعت اخیر')}</Typography></Box>; }
function GlassLine({ def, locale, size }: Props) { const p = profile(size), values = (def.mock.values as number[] | undefined) ?? spark, summary = s(def.mock.summary, '24.8 °C'), isArea = def.visual === 'area'; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto minmax(0,1fr) auto', gap: .75, direction: 'ltr' }}><ChartHeader summary={summary} locale={locale}/><GlassPlate sx={{ p: p.large ? 1 : .65, minHeight: 0 }}><LuminousChart values={values} color={isArea ? C.violet : C.blue} fill dots={p.large}/></GlassPlate><Box sx={{ display: 'flex', justifyContent: 'space-between', fontSize: 9, color: C.faint }}><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></Box></Box>; }
function GlassBar({ def, locale, size }: Props) { const p = profile(size), values = (def.mock.values as number[] | undefined) ?? bars, max = Math.max(...values); return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto minmax(0,1fr) auto', gap: .75, direction: 'ltr' }}><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: p.large ? 20 : 16, fontWeight: 810 }}>{tr(locale, 'Weekly output', 'خروجی هفتگی')}</Typography><StatusText>{tr(locale, 'Stable', 'پایدار')}</StatusText></Box><GlassPlate sx={{ p: .9, minHeight: 0, display: 'flex', alignItems: 'end', gap: p.large ? .9 : .65 }}>{values.map((v, i) => <Box key={i} sx={{ flex: 1, height: `${Math.max(10, v / max * 100)}%`, minHeight: 14, borderRadius: '6px 6px 2px 2px', background: i === values.length - 2 ? `linear-gradient(180deg,${C.violet},${C.violet}55)` : `linear-gradient(180deg,${C.blue},${C.blue}45)`, boxShadow: i === values.length - 2 ? `0 0 18px ${C.violet}35` : 'none' }}/>)}</GlassPlate><Box sx={{ display: 'grid', gridTemplateColumns: `repeat(${values.length},1fr)`, fontSize: 8.8, color: C.faint, textAlign: 'center' }}>{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((x, i) => <span key={`${x}${i}`}>{x}</span>)}</Box></Box>; }
function GlassHistogram({ locale, size }: Props) { const p = profile(size), values = [2, 5, 9, 15, 20, 17, 12, 8, 4, 2], max = 20; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto minmax(0,1fr) auto', gap: .8, direction: 'ltr' }}><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: p.large ? 20 : 16, fontWeight: 810 }}>{tr(locale, 'Distribution', 'توزیع')}</Typography><Typography sx={{ fontSize: 9.5, color: C.faint }}>n=128</Typography></Box><GlassPlate sx={{ p: .9, minHeight: 0, display: 'flex', alignItems: 'end', gap: .25 }}>{values.map((v, i) => <Box key={i} sx={{ flex: 1, height: `${v / max * 100}%`, minHeight: 5, borderRadius: '4px 4px 1px 1px', background: `linear-gradient(180deg,rgba(125,211,252,${.35 + v / max * .55}),rgba(196,181,253,.18))` }}/>)}</GlassPlate><Box sx={{ display: 'flex', justifyContent: 'space-between', fontSize: 8.8, color: C.faint }}><span>LOW</span><span>MEDIAN</span><span>HIGH</span></Box></Box>; }
function GlassDonut({ def, locale, size }: Props) { const p = profile(size), value = n(def.mock.value, 72), r = 42, c = 2 * Math.PI * r; return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: p.wide && !p.large ? 'auto 1fr' : '1fr', gridTemplateRows: p.wide && !p.large ? '1fr' : p.large ? '1fr auto' : '1fr', gap: 1, alignItems: 'center', direction: 'ltr' }}><Box sx={{ display: 'grid', placeItems: 'center' }}><Box sx={{ position: 'relative', width: p.large ? 168 : 136, height: p.large ? 168 : 136 }}><svg viewBox="0 0 120 120" width="100%" height="100%"><defs><linearGradient id="glass-donut" x1="0" x2="1"><stop offset="0" stopColor={C.blue}/><stop offset="1" stopColor={C.violet}/></linearGradient></defs><circle cx="60" cy="60" r={r} fill="rgba(255,255,255,.025)" stroke="rgba(255,255,255,.08)" strokeWidth="13"/><circle cx="60" cy="60" r={r} fill="none" stroke="url(#glass-donut)" strokeWidth="13" strokeLinecap="round" strokeDasharray={`${c * value / 100} ${c}`} transform="rotate(-90 60 60)"/></svg><Box sx={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', textAlign: 'center' }}><Box><Typography sx={{ fontSize: 30, fontWeight: 830 }}>{value}%</Typography><Typography sx={{ fontSize: 9, color: C.muted }}>{tr(locale, 'USED', 'مصرف')}</Typography></Box></Box></Box></Box>{p.wide && !p.large ? <Box><MiniStat label={tr(locale, 'Free', 'آزاد')} value={`${100 - value}%`}/><Box sx={{ mt: .7 }}><MiniStat label={tr(locale, 'Capacity', 'ظرفیت')} value="12.8 GB" accent/></Box></Box> : p.large && <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label={tr(locale, 'Used', 'مصرف')} value={`${value}%`} accent/><MiniStat label={tr(locale, 'Free', 'آزاد')} value={`${100 - value}%`}/><MiniStat label={tr(locale, 'Change', 'تغییر')} value="+3.2%"/></Box>}</Box>; }
function GlassHeatmap({ locale, size }: Props) { const p = profile(size); return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto minmax(0,1fr) auto', gap: .8, direction: 'ltr' }}><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: p.large ? 19 : 15, fontWeight: 810 }}>{tr(locale, 'Intensity map', 'نقشه شدت')}</Typography><Typography sx={{ fontSize: 9, color: C.faint }}>7D × 4 WINDOWS</Typography></Box><GlassPlate sx={{ p: .75, minHeight: 0, display: 'grid', gridTemplateColumns: 'repeat(7,1fr)', gridTemplateRows: 'repeat(4,1fr)', gap: .35 }}>{heat.flat().map((v, i) => <Box key={i} sx={{ borderRadius: '4px', background: `linear-gradient(145deg,rgba(125,211,252,${.12 + v * .16}),rgba(196,181,253,${.055 + v * .11}))`, border: v > .75 ? '1px solid rgba(251,191,36,.52)' : '1px solid rgba(214,246,255,.065)', boxShadow: v > .85 ? '0 0 12px rgba(251,191,36,.18)' : 'none' }}/>)}</GlassPlate><Box sx={{ display: 'flex', justifyContent: 'space-between', fontSize: 8.8, color: C.faint }}><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></Box></Box>; }
function GlassTimeline({ locale, size }: Props) { const p = profile(size), rows = ['Pump', 'Valve', 'Fan', 'Mode']; const states = [[0, 0, 1, 0, 0, 2, 0], [0, 0, 0, 0, 1, 1, 0], [0, 1, 1, 0, 0, 0, 2], [2, 2, 0, 0, 0, 1, 1]]; const tone = (v: number) => v === 2 ? C.danger : v === 1 ? C.warning : C.success; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto minmax(0,1fr) auto', gap: .8, direction: 'ltr' }}><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: p.large ? 18 : 15, fontWeight: 810 }}>{tr(locale, 'State history', 'تاریخچه وضعیت')}</Typography><StatusText>{tr(locale, '4 channels', '۴ کانال')}</StatusText></Box><GlassPlate sx={{ p: .9, minHeight: 0, display: 'grid', alignContent: 'center', gap: p.large ? .9 : .6 }}>{rows.map((row, ri) => <Box key={row} sx={{ display: 'grid', gridTemplateColumns: '46px repeat(7,1fr)', gap: .35, alignItems: 'center' }}><Typography sx={{ fontSize: 9, color: C.muted }}>{row}</Typography>{states[ri].map((v, i) => <Box key={i} sx={{ height: p.large ? 14 : 10, borderRadius: '3px', bgcolor: `${tone(v)}${v === 0 ? 'aa' : 'cc'}`, boxShadow: v === 2 ? `0 0 10px ${C.danger}44` : 'none' }}/>)}</Box>)}</GlassPlate><Box sx={{ display: 'flex', justifyContent: 'space-between', fontSize: 8.5, color: C.faint, paddingInlineStart: '50px' }}><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></Box></Box>; }
function MapCanvas({ route = false, large = false }: {
    route?: boolean;
    large?: boolean;
}) { return <Box sx={{ height: '100%', minHeight: 0, position: 'relative', overflow: 'hidden', borderRadius: '14px', border: '1px solid rgba(255,255,255,.13)', background: 'linear-gradient(145deg,rgba(4,17,35,.58),rgba(10,42,58,.36))' }}><svg viewBox="0 0 420 250" width="100%" height="100%" preserveAspectRatio="none"><rect width="420" height="250" fill="transparent"/>{[40, 100, 170, 235, 315, 380].map((x, i) => <path key={`v${i}`} d={`M${x} -20 C ${x + 30} 55 ${x - 18} 145 ${x + 25} 280`} fill="none" stroke="rgba(255,255,255,.07)" strokeWidth={i % 2 ? 3 : 5}/>)}{[34, 92, 150, 212].map((y, i) => <path key={`h${i}`} d={`M-25 ${y} C 110 ${y - 24} 265 ${y + 28} 450 ${y - 8}`} fill="none" stroke="rgba(255,255,255,.065)" strokeWidth={i % 2 ? 3 : 5}/>)}<path d={route ? 'M22 192 C88 124 132 168 180 116 S286 72 382 128' : 'M42 178 C116 130 168 150 220 106 S324 94 386 78'} fill="none" stroke={C.blue} strokeWidth="4" strokeLinecap="round"/><path d={route ? 'M22 192 C88 124 132 168 180 116 S286 72 382 128' : 'M42 178 C116 130 168 150 220 106 S324 94 386 78'} fill="none" stroke="rgba(255,255,255,.52)" strokeWidth="1" strokeDasharray="3 8"/>{[{ x: 96, y: 145 }, { x: 221, y: 106 }, { x: 341, y: 94 }].map((pt, i) => <g key={i}><circle cx={pt.x} cy={pt.y} r={large ? 12 : 9} fill={C.blue} opacity=".16"/><circle cx={pt.x} cy={pt.y} r={large ? 5 : 4} fill={i === 1 ? C.violet : C.blue}/></g>)}</svg><Box sx={{ position: 'absolute', left: 10, top: 10, px: .7, py: .4, borderRadius: '8px', border: '1px solid rgba(255,255,255,.12)', bgcolor: 'rgba(2,12,28,.35)', fontSize: 9, color: C.muted }}>GPS · LIVE</Box>{large && <Box sx={{ position: 'absolute', right: 10, bottom: 10, px: .7, py: .4, borderRadius: '8px', border: '1px solid rgba(255,255,255,.12)', bgcolor: 'rgba(2,12,28,.35)', fontSize: 9, color: C.muted }}>{route ? '12.4 km · 36 min' : '3 assets online'}</Box>}</Box>; }
function GlassMap({ def, size }: Props) { const p = profile(size), route = def.visual === 'route'; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: p.large ? 'minmax(0,1fr) auto' : '1fr', gap: .8, direction: 'ltr' }}><MapCanvas route={route} large={p.large}/>{p.large && <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label="LAT" value="35.7219° N"/><MiniStat label="LNG" value="51.3347° E"/><MiniStat label={route ? 'DISTANCE' : 'ACCURACY'} value={route ? '12.4 km' : '±4.2 m'} accent/></Box>}</Box>; }
function GlassCoordinates({ def, locale, size }: Props) { const p = profile(size), lat = s(def.mock.lat, '35.7219° N'), lng = s(def.mock.lng, '51.3347° E'), accuracy = s(def.mock.accuracy, '4.2 m'); if (p.compact)
    return <Box sx={{ height: '100%', display: 'grid', alignContent: 'center', gap: .65, direction: 'ltr' }}><MiniStat label="LAT" value={lat}/><MiniStat label="LNG" value={lng}/><MiniStat label={tr(locale, 'Accuracy', 'دقت')} value={accuracy} accent/></Box>; if (p.wide && !p.large)
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: '1fr 1fr .7fr', gap: .75, alignItems: 'center', direction: 'ltr' }}><MiniStat label="LATITUDE" value={lat}/><MiniStat label="LONGITUDE" value={lng}/><MiniStat label={tr(locale, 'Accuracy', 'دقت')} value={accuracy} accent/></Box>; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'minmax(0,1fr) auto', gap: .8, direction: 'ltr' }}><MapCanvas large/><Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr .7fr', gap: .7 }}><MiniStat label="LAT" value={lat}/><MiniStat label="LNG" value={lng}/><MiniStat label={tr(locale, 'Accuracy', 'دقت')} value={accuracy} accent/></Box></Box>; }
function GlassCompass({ def, locale, size }: Props) { const p = profile(size), value = n(def.mock.value, 327), card = value >= 337.5 || value < 22.5 ? 'N' : value < 67.5 ? 'NE' : value < 112.5 ? 'E' : value < 157.5 ? 'SE' : value < 202.5 ? 'S' : value < 247.5 ? 'SW' : value < 292.5 ? 'W' : 'NW'; const face = (dia: number) => <Box sx={{ width: dia, height: dia, borderRadius: '50%', position: 'relative', display: 'grid', placeItems: 'center', background: 'radial-gradient(circle,rgba(255,255,255,.06),rgba(255,255,255,.015) 58%,transparent 60%)', border: '1px solid rgba(255,255,255,.13)', boxShadow: 'inset 0 0 34px rgba(125,211,252,.06)' }}>{['N', 'E', 'S', 'W'].map((x, i) => <Typography key={x} sx={{ position: 'absolute', fontSize: 9.5, fontWeight: 800, color: x === 'N' ? C.blue : C.faint, top: i === 0 ? 8 : i === 2 ? undefined : '50%', bottom: i === 2 ? 8 : undefined, left: i === 3 ? 9 : i === 1 ? undefined : '50%', right: i === 1 ? 9 : undefined, transform: i === 0 || i === 2 ? 'translateX(-50%)' : i === 1 || i === 3 ? 'translateY(-50%)' : undefined }}>{x}</Typography>)}<Box sx={{ position: 'absolute', width: 3, height: '37%', top: '13%', left: 'calc(50% - 1.5px)', transformOrigin: '50% 100%', transform: `rotate(${value}deg)`, background: `linear-gradient(180deg,${C.violet},${C.blue})`, boxShadow: `0 0 12px ${C.blue}66` }}/><Box sx={{ width: dia > 160 ? 80 : 64, height: dia > 160 ? 58 : 48, borderRadius: '12px', display: 'grid', placeItems: 'center', textAlign: 'center', background: 'rgba(2,12,28,.32)', border: '1px solid rgba(255,255,255,.12)' }}><Box><Typography sx={{ fontSize: dia > 160 ? 30 : 24, fontWeight: 820, lineHeight: .95 }}>{value}°</Typography><Typography sx={{ fontSize: 9, color: C.muted }}>{card}</Typography></Box></Box></Box>; if (p.compact)
    return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', direction: 'ltr' }}>{face(122)}</Box>; if (p.wide && !p.large)
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: '150px 1fr', alignItems: 'center', gap: 1.2, direction: 'ltr' }}>{face(142)}<Box sx={{ display: 'grid', gap: .7 }}><MiniStat label={tr(locale, 'Heading', 'جهت')} value={`${value}°`} accent/><MiniStat label={tr(locale, 'Direction', 'جهت اصلی')} value={card}/></Box></Box>; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: '1fr auto', gap: .8, direction: 'ltr' }}><Box sx={{ display: 'grid', placeItems: 'center' }}>{face(190)}</Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label={tr(locale, 'Heading', 'جهت')} value={`${value}°`} accent/><MiniStat label={tr(locale, 'Direction', 'جهت اصلی')} value={card}/><MiniStat label={tr(locale, 'Accuracy', 'دقت')} value="±2°"/></Box></Box>; }
function GlassButton({ locale, size }: Props) { const p = profile(size), [sent, setSent] = useState(false); const trigger = () => { setSent(true); window.setTimeout(() => setSent(false), 1200); }; const btn = <Button onClick={trigger} variant="contained" sx={{ textTransform: 'none', fontWeight: 800, borderRadius: '11px', background: `linear-gradient(120deg,${C.blue},${C.violet})`, color: '#07111e', boxShadow: `0 8px 24px ${C.blue}2f`, '&:hover': { background: `linear-gradient(120deg,${C.blue},${C.violet})` } }}>{sent ? tr(locale, 'Queued ✓', 'در صف ✓') : tr(locale, 'Send command', 'ارسال فرمان')}</Button>; if (p.compact)
    return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', textAlign: 'center' }}><Box>{btn}<Typography sx={{ mt: .7, fontSize: 9.5, color: sent ? C.success : C.muted }}>{sent ? tr(locale, 'ACK pending', 'در انتظار تأیید') : tr(locale, 'Ready', 'آماده')}</Typography></Box></Box>; if (!p.large)
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: '1fr auto', alignItems: 'center', gap: 1.3 }}><Box><Typography sx={{ fontSize: 17, fontWeight: 820 }}>{tr(locale, 'Operational command', 'فرمان عملیاتی')}</Typography><Typography sx={{ mt: .35, fontSize: 10.5, color: C.muted }}>{tr(locale, 'RPC / downlink to target device', 'RPC / Downlink برای دستگاه مقصد')}</Typography></Box>{btn}</Box>; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto auto minmax(0,1fr) auto', gap: .9 }}><Box><Typography sx={{ fontSize: 22, fontWeight: 830 }}>{tr(locale, 'Operational command', 'فرمان عملیاتی')}</Typography><Typography sx={{ mt: .3, fontSize: 10.5, color: C.muted }}>{tr(locale, 'Send a predefined RPC/downlink action and monitor acknowledgement.', 'ارسال فرمان و مشاهده تأیید دستگاه.')}</Typography></Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label="TARGET" value="Device"/><MiniStat label="TIMEOUT" value="5 sec"/><MiniStat label="METHOD" value="RPC" accent/></Box><GlassPlate sx={{ p: 1, minHeight: 0, display: 'grid', alignContent: 'center' }}><StatusText color={sent ? C.warning : C.success}>{sent ? tr(locale, 'Command queued · waiting for ACK', 'فرمان در صف · منتظر ACK') : tr(locale, 'Last ACK · 09:41:32 · 182 ms', 'آخرین ACK · 09:41:32 · 182 ms')}</StatusText></GlassPlate>{btn}</Box>; }
function SwitchKnob({ checked, onChange }: {
    checked: boolean;
    onChange: () => void;
}) { return <Box onClick={onChange} sx={{ width: 72, height: 38, borderRadius: '19px', p: .45, cursor: 'pointer', background: checked ? `linear-gradient(110deg,${C.blue}55,${C.success}44)` : 'rgba(255,255,255,.07)', border: `1px solid ${checked ? 'rgba(94,234,212,.44)' : 'rgba(255,255,255,.12)'}`, boxShadow: checked ? `inset 0 0 20px ${C.success}12` : 'none' }}><Box sx={{ width: 29, height: 29, borderRadius: '50%', transform: `translateX(${checked ? 33 : 0}px)`, transition: 'transform .2s ease', background: checked ? 'linear-gradient(145deg,#eaffff,#5eead4)' : 'linear-gradient(145deg,#e4edf1,#8093a0)', boxShadow: checked ? `0 0 20px ${C.success}66` : '0 4px 12px rgba(0,0,0,.22)' }}/></Box>; }
function GlassSwitch({ def, locale, size }: Props) { const p = profile(size), [checked, setChecked] = useState(Boolean(def.mock.value ?? true)), isLock = def.id === 'door-lock', isSiren = def.id === 'siren'; const state = checked ? (isLock ? tr(locale, 'Locked', 'قفل') : isSiren ? tr(locale, 'Beacon active', 'هشدار فعال') : tr(locale, 'Output enabled', 'خروجی فعال')) : (isLock ? tr(locale, 'Unlocked', 'باز') : isSiren ? tr(locale, 'Beacon standby', 'هشدار آماده') : tr(locale, 'Output disabled', 'خروجی غیرفعال')); if (p.compact)
    return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', textAlign: 'center' }}><Box><SwitchKnob checked={checked} onChange={() => setChecked(v => !v)}/><Typography sx={{ mt: .7, fontSize: 12.5, fontWeight: 800, color: checked ? C.success : C.muted }}>{state}</Typography></Box></Box>; if (!p.large)
    return <Box sx={{ height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 1.3 }}><Box><Typography sx={{ fontSize: 19, fontWeight: 830 }}>{state}</Typography><Typography sx={{ mt: .3, fontSize: 10.5, color: C.muted }}>{isLock ? tr(locale, 'Door access', 'دسترسی درب') : isSiren ? tr(locale, 'Safety output', 'خروجی ایمنی') : tr(locale, 'Relay output', 'خروجی رله')}</Typography></Box><SwitchKnob checked={checked} onChange={() => setChecked(v => !v)}/></Box>; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto auto minmax(0,1fr)', gap: 1 }}><Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><Box><Typography sx={{ fontSize: 26, fontWeight: 830 }}>{state}</Typography><Box sx={{ mt: .5 }}><StatusText>{checked ? tr(locale, 'Stable', 'پایدار') : tr(locale, 'Standby', 'آماده')}</StatusText></Box></Box><SwitchKnob checked={checked} onChange={() => setChecked(v => !v)}/></Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label={tr(locale, 'Last change', 'آخرین تغییر')} value="09:42"/><MiniStat label={tr(locale, 'Source', 'منبع')} value="Dashboard"/><MiniStat label={tr(locale, 'State', 'وضعیت')} value={checked ? 'ON' : 'OFF'} accent/></Box><GlassPlate sx={{ p: .9, minHeight: 0, display: 'flex', alignItems: 'center', gap: .35 }}>{[1, 1, 1, 0, 1, 1, 1, checked ? 1 : 0].map((x, i) => <Box key={i} sx={{ height: 10, flex: 1, borderRadius: '3px', bgcolor: x ? `${C.success}aa` : 'rgba(255,255,255,.08)' }}/>)}</GlassPlate></Box>; }
function GlassSlider({ def, locale, size }: Props) { const p = profile(size), [value, setValue] = useState(n(def.mock.value, 65)), unit = s(def.mock.unit, '%'); return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: p.large ? 'auto auto minmax(0,1fr)' : '1fr', gap: 1, direction: 'ltr' }}><Box sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}><Box sx={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between' }}><Typography sx={{ fontSize: p.large ? 38 : 31, fontWeight: 830 }}>{value}<Box component="span" sx={{ fontSize: 12, ml: .45, color: C.muted }}>{unit}</Box></Typography><Typography sx={{ fontSize: 9.5, color: C.faint }}>0 — 100</Typography></Box><Slider value={value} onChange={(_, v) => setValue(v as number)} sx={{ color: C.blue, py: 1, '& .MuiSlider-rail': { opacity: 1, background: 'rgba(255,255,255,.11)' }, '& .MuiSlider-track': { border: 'none', background: `linear-gradient(90deg,${C.blue},${C.violet})` }, '& .MuiSlider-thumb': { width: 17, height: 17, background: '#dffaff', boxShadow: `0 0 18px ${C.blue}88`, border: '2px solid rgba(125,211,252,.7)' } }}/></Box>{p.large && <><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label={tr(locale, 'Low', 'کم')} value="0"/><MiniStat label={tr(locale, 'Target', 'هدف')} value={`${value}${unit}`} accent/><MiniStat label={tr(locale, 'High', 'زیاد')} value="100"/></Box><GlassPlate sx={{ p: .8, minHeight: 0 }}><LuminousChart values={[30, 35, 42, 49, 52, 57, 61, value, value]} color={C.blue} fill/></GlassPlate></>}</Box>; }
function GlassInput({ def, locale, size }: Props) { const p = profile(size), [value, setValue] = useState(String(def.mock.value ?? '22.5')), [applied, setApplied] = useState(false), unit = s(def.mock.unit, ''); const apply = () => setApplied(true); const field = <TextField value={value} onChange={e => { setValue(e.target.value); setApplied(false); }} size="small" fullWidth label={tr(locale, 'Target value', 'مقدار هدف')} inputProps={{ dir: 'ltr' }} sx={{ '& .MuiOutlinedInput-root': { color: '#f8fbff', borderRadius: '11px', background: 'rgba(255,255,255,.045)' }, '& .MuiInputLabel-root': { color: C.muted }, '& .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,.14)' }, '& .MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(125,211,252,.45)' } }}/>; if (!p.large)
    return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center' }}><Box sx={{ width: '100%' }}>{field}{p.wide && <Box sx={{ mt: .7, display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: 9.5, color: C.muted }}>{unit}</Typography><StatusText color={applied ? C.success : C.faint}>{applied ? tr(locale, 'Applied', 'اعمال شد') : tr(locale, 'Edit value', 'ویرایش مقدار')}</StatusText></Box>}</Box></Box>; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto auto minmax(0,1fr)', gap: 1 }}><Box sx={{ display: 'grid', gridTemplateColumns: '1fr 112px', gap: .8 }}>{field}<Button onClick={apply} variant="contained" sx={{ borderRadius: '11px', textTransform: 'none', fontWeight: 800, background: `linear-gradient(120deg,${C.blue},${C.violet})`, color: '#07111e' }}>{tr(locale, 'Apply', 'اعمال')}</Button></Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label={tr(locale, 'Current', 'فعلی')} value={`21.8 ${unit}`}/><MiniStat label={tr(locale, 'Target', 'هدف')} value={`${value} ${unit}`} accent/><MiniStat label={tr(locale, 'Delta', 'اختلاف')} value={`+0.7 ${unit}`}/></Box><GlassPlate sx={{ p: 1, minHeight: 0, display: 'grid', alignContent: 'center' }}><StatusText color={applied ? C.success : C.warning}>{applied ? tr(locale, 'Setpoint applied to device', 'مقدار هدف به دستگاه اعمال شد') : tr(locale, 'Pending local edit', 'ویرایش محلی در انتظار اعمال')}</StatusText></GlassPlate></Box>; }
function GlassThermostat({ def, locale, size }: Props) { const p = profile(size), [target, setTarget] = useState(n(def.mock.value, 22)); const circle = <Box sx={{ width: p.large ? 164 : p.compact ? 122 : 142, height: p.large ? 164 : p.compact ? 122 : 142, borderRadius: '50%', display: 'grid', placeItems: 'center', position: 'relative', background: 'radial-gradient(circle at 38% 30%,rgba(255,255,255,.16),rgba(125,211,252,.055) 48%,rgba(255,255,255,.015) 70%)', border: '1px solid rgba(255,255,255,.15)', boxShadow: 'inset 0 0 38px rgba(125,211,252,.07)' }}><Box sx={{ textAlign: 'center' }}><Typography sx={{ fontSize: p.large ? 36 : 31, fontWeight: 830, lineHeight: .9 }}>{target}°</Typography><Typography sx={{ mt: .35, fontSize: 9.5, color: C.muted }}>{tr(locale, 'SETPOINT', 'هدف')}</Typography></Box><Box sx={{ position: 'absolute', left: 12, right: 12, bottom: 14, display: 'flex', justifyContent: 'space-between' }}><Box component="button" onClick={() => setTarget(v => clamp(v - 1, 10, 35))} sx={{ border: 0, width: 28, height: 28, borderRadius: '50%', color: '#fff', background: 'rgba(255,255,255,.08)', cursor: 'pointer' }}>−</Box><Box component="button" onClick={() => setTarget(v => clamp(v + 1, 10, 35))} sx={{ border: 0, width: 28, height: 28, borderRadius: '50%', color: '#fff', background: 'rgba(255,255,255,.08)', cursor: 'pointer' }}>+</Box></Box></Box>; if (p.compact)
    return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center' }}>{circle}</Box>; if (!p.large)
    return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: 'auto 1fr', alignItems: 'center', gap: 1.3, direction: 'ltr' }}>{circle}<Box><StatusText>{tr(locale, 'Heating idle', 'گرمایش آماده')}</StatusText><Box sx={{ mt: .8, display: 'grid', gap: .6 }}><MiniStat label={tr(locale, 'Room', 'اتاق')} value="21.6 °C"/><MiniStat label={tr(locale, 'Target', 'هدف')} value={`${target} °C`} accent/></Box></Box></Box>; return <Box sx={{ height: '100%', display: 'grid', gridTemplateColumns: '190px 1fr', gap: 1.3, alignItems: 'center', direction: 'ltr' }}>{circle}<Box><Typography sx={{ fontSize: 20, fontWeight: 820 }}>{tr(locale, 'Climate setpoint', 'تنظیم دما')}</Typography><Box sx={{ mt: .7 }}><StatusText>{tr(locale, 'Room stable', 'دمای اتاق پایدار')}</StatusText></Box><Box sx={{ mt: 1, display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label={tr(locale, 'Room', 'اتاق')} value="21.6 °C"/><MiniStat label={tr(locale, 'Target', 'هدف')} value={`${target} °C`} accent/><MiniStat label={tr(locale, 'Humidity', 'رطوبت')} value="46%"/></Box><GlassPlate sx={{ mt: 1, p: .8, height: 82 }}><LuminousChart values={[21.0, 21.2, 21.5, 21.4, 21.6, 21.7, 21.6, 21.6]} color={C.blue} fill/></GlassPlate></Box></Box>; }
function GlassColor({ locale, size }: Props) { const p = profile(size), colors = ['#22d3ee', '#60a5fa', '#a78bfa', '#f472b6', '#fb7185', '#fbbf24', '#34d399'], [color, setColor] = useState(colors[2]), [brightness, setBrightness] = useState(72); return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: p.large ? 'auto auto auto minmax(0,1fr)' : 'auto auto 1fr', gap: .85, direction: 'ltr' }}><Box sx={{ height: p.large ? 76 : 48, borderRadius: '13px', background: `radial-gradient(circle at 35% 25%,rgba(255,255,255,.65),transparent 18%), linear-gradient(100deg,${color},${color}55)`, boxShadow: `inset 0 0 22px rgba(255,255,255,.14),0 0 24px ${color}35`, border: '1px solid rgba(255,255,255,.15)' }}/><Box sx={{ display: 'grid', gridTemplateColumns: `repeat(${colors.length},1fr)`, gap: .55 }}>{colors.map(c => <Box key={c} onClick={() => setColor(c)} sx={{ height: p.large ? 26 : 22, borderRadius: '7px', bgcolor: c, cursor: 'pointer', border: c === color ? '2px solid rgba(255,255,255,.9)' : '1px solid rgba(255,255,255,.12)', boxShadow: c === color ? `0 0 12px ${c}77` : 'none' }}/>)}</Box><Box><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: 9.5, color: C.muted }}>{tr(locale, 'Brightness', 'روشنایی')}</Typography><Typography sx={{ fontSize: 9.5, color: C.muted }}>{brightness}%</Typography></Box><Slider value={brightness} onChange={(_, v) => setBrightness(v as number)} sx={{ color, py: .6, '& .MuiSlider-thumb': { width: 15, height: 15, boxShadow: `0 0 14px ${color}` } }}/></Box>{p.large && <GlassPlate sx={{ p: .8, minHeight: 0, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: .8, alignItems: 'center' }}><MiniStat label="HEX" value={color.toUpperCase()} accent/><MiniStat label={tr(locale, 'Mode', 'حالت')} value={tr(locale, 'Ambient', 'محیطی')}/></GlassPlate>}</Box>; }
function GlassDirection({ locale, size }: Props) { const p = profile(size), [dir, setDir] = useState('STOP'), buttons = [['↑', 'UP'], ['←', 'LEFT'], ['■', 'STOP'], ['→', 'RIGHT'], ['↓', 'DOWN']], keySize = p.large ? 62 : p.compact ? 42 : 48, gap = p.large ? .75 : .5; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: p.large ? 'minmax(0,1fr) auto' : '1fr', gap: .9 }}><Box sx={{ display: 'grid', placeItems: 'center' }}><GlassPlate sx={{ p: p.large ? 1.25 : .8, borderRadius: p.large ? '18px' : '14px' }}><Box sx={{ display: 'grid', gridTemplateColumns: `repeat(3,${keySize}px)`, gridTemplateRows: `repeat(3,${keySize}px)`, gap }}>{buttons.map(([glyph, name]) => { const pos = name === 'UP' ? { gridColumn: 2, gridRow: 1 } : name === 'LEFT' ? { gridColumn: 1, gridRow: 2 } : name === 'STOP' ? { gridColumn: 2, gridRow: 2 } : name === 'RIGHT' ? { gridColumn: 3, gridRow: 2 } : { gridColumn: 2, gridRow: 3 }; const active = dir === name; return <Box component="button" key={name} onClick={() => setDir(name)} aria-label={name} sx={{ ...pos, borderRadius: p.large ? '15px' : '11px', border: `1px solid ${active ? 'rgba(125,211,252,.48)' : 'rgba(214,246,255,.10)'}`, background: active ? 'linear-gradient(145deg,rgba(125,211,252,.22),rgba(196,181,253,.13))' : 'linear-gradient(145deg,rgba(255,255,255,.045),rgba(3,18,31,.24))', color: active ? C.blue : '#eefaff', cursor: 'pointer', fontSize: p.large ? 25 : 18, boxShadow: active ? `0 0 16px ${C.blue}2d, inset 0 1px 0 rgba(255,255,255,.08)` : 'inset 0 1px 0 rgba(255,255,255,.035)' }}>{glyph}</Box>; })}</Box></GlassPlate></Box>{p.large && <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: .7 }}><MiniStat label={tr(locale, 'Last command', 'آخرین فرمان')} value={dir} accent/><MiniStat label={tr(locale, 'Latency', 'تأخیر')} value="84 ms"/></Box>}</Box>; }
function rowsFor(mode: TableMode) { if (mode === 'measurement-list')
    return [['24.8 °C', '09:44'], ['24.7 °C', '09:43'], ['24.9 °C', '09:42'], ['24.6 °C', '09:41'], ['24.8 °C', '09:40']]; if (mode === 'alarms')
    return [['High temp', 'Critical', '09:42'], ['Door open', 'Warning', '09:37'], ['Battery low', 'Info', '08:54'], ['Smoke', 'Normal', '08:12']]; if (mode === 'events')
    return [['Valve V-02', 'Opened', '09:40'], ['Pump M-01', 'Started', '09:31'], ['Mode', 'Auto', '08:57'], ['Setpoint', 'Updated', '08:43']]; if (mode === 'logs')
    return [['gateway-01', 'connected', '09:44:21'], ['pump-04', 'rpc ack', '09:44:02'], ['sensor-18', 'telemetry', '09:43:58'], ['edge-02', 'heartbeat', '09:43:41']]; return [['Pump-04', 'Online', '284 W'], ['Node-18', 'Warning', '64%'], ['Valve-02', 'Open', '82%'], ['Sensor-12', 'Online', '24.8 °C'], ['GW-01', 'Online', '18 ms']]; }
function statusColor(cell: string) { const x = cell.toLowerCase(); return x.includes('critical') ? C.danger : x.includes('warn') ? C.warning : x.includes('online') || x.includes('open') || x.includes('started') || x.includes('connected') || x.includes('ack') ? C.success : C.muted; }
function GlassTable({ locale, mode, size }: Props & {
    mode: TableMode;
}) { const p = profile(size), rows = rowsFor(mode), maxRows = p.large ? rows.length : Math.min(4, rows.length), visible = rows.slice(0, maxRows); return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: p.large ? 'auto minmax(0,1fr) auto' : 'auto minmax(0,1fr)', gap: .7, direction: 'ltr' }}><Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><StatusText>{mode === 'alarms' ? tr(locale, '2 require attention', '۲ مورد نیازمند بررسی') : tr(locale, 'Live feed', 'داده زنده')}</StatusText><Typography sx={{ fontSize: 9, color: C.faint }}>{rows.length} ROWS</Typography></Box><GlassPlate sx={{ minHeight: 0, overflow: 'hidden', p: .35, display: 'grid', gridTemplateRows: p.large ? `repeat(${visible.length},minmax(34px,1fr))` : `repeat(${visible.length},auto)`, alignContent: 'stretch' }}>{visible.map((row, i) => <Box key={i} sx={{ display: 'grid', gridTemplateColumns: `repeat(${row.length},minmax(0,1fr))`, gap: .6, alignItems: 'center', px: .8, py: p.large ? .55 : .6, borderBottom: i < visible.length - 1 ? '1px solid rgba(255,255,255,.065)' : 'none', background: mode === 'alarms' && i === 0 ? 'linear-gradient(90deg,rgba(251,113,133,.10),transparent)' : i % 2 ? 'rgba(255,255,255,.012)' : 'transparent' }}>{row.map((cell, j) => <Typography key={j} sx={{ fontSize: p.large ? 11.2 : 10, fontWeight: j === 0 ? 760 : 650, color: j === 1 ? statusColor(cell) : j === 0 ? '#f7fbff' : C.muted, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', textAlign: j === row.length - 1 ? 'right' : 'left' }}>{cell}</Typography>)}</Box>)}</GlassPlate>{p.large && <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .65 }}><MiniStat label={tr(locale, 'Healthy', 'سالم')} value={mode === 'alarms' ? '2 clear' : '4 online'} accent/><MiniStat label={tr(locale, 'Attention', 'نیازمند بررسی')} value={mode === 'alarms' ? '2 active' : '1 warn'}/><MiniStat label={tr(locale, 'Refresh', 'به‌روزرسانی')} value="LIVE · 2s"/></Box>}</Box>; }
function GlassClock({ locale, size }: Props) { const p = profile(size); return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: p.large ? '1fr auto' : '1fr', placeItems: 'center', gap: 1, textAlign: 'center', direction: 'ltr' }}><Box><Typography sx={{ fontSize: p.large ? 68 : p.compact ? 40 : 52, fontWeight: 330, letterSpacing: '-.065em', lineHeight: .9, textShadow: '0 10px 28px rgba(0,0,0,.2)' }}>09:44</Typography><Typography sx={{ mt: .7, fontSize: p.large ? 13 : 10.5, color: C.muted }}>{locale === 'fa' ? 'چهارشنبه، ۱۵ مهر ۱۴۰۵' : 'Wednesday, Oct 7'}</Typography></Box>{p.large && <Box sx={{ width: '100%', display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .7 }}><MiniStat label="SITE" value="Factory A"/><MiniStat label="TZ" value="UTC+03:30" accent/><MiniStat label="SYNC" value="NTP · 12 ms"/></Box>}</Box>; }
function GlassText({ locale, size }: Props) { const p = profile(size); if (p.compact)
    return <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'center', direction: locale === 'fa' ? 'rtl' : 'ltr', textAlign: locale === 'fa' ? 'right' : 'left' }}><Typography sx={{ fontSize: 17, fontWeight: 820 }}>{tr(locale, 'Server room status', 'وضعیت اتاق سرور')}</Typography><Typography sx={{ mt: .7, fontSize: 10.5, lineHeight: 1.65, color: C.muted, display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>{tr(locale, 'All sensors are within normal range. Latest telemetry arrived less than a minute ago.', 'همه سنسورها در محدوده عادی هستند. آخرین داده کمتر از یک دقیقه قبل دریافت شده است.')}</Typography></Box>; return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: 'auto auto minmax(0,1fr)', gap: .85, direction: locale === 'fa' ? 'rtl' : 'ltr', textAlign: locale === 'fa' ? 'right' : 'left' }}><Box><Typography sx={{ fontSize: p.large ? 22 : 18, fontWeight: 830 }}>{tr(locale, 'Server room status', 'وضعیت اتاق سرور')}</Typography><Typography sx={{ mt: .45, fontSize: 11, lineHeight: 1.7, color: C.muted }}>{tr(locale, 'All sensors are within their normal ranges. Latest telemetry was received less than a minute ago.', 'همه سنسورها در محدوده عادی هستند. آخرین بسته داده کمتر از یک دقیقه قبل دریافت شده است.')}</Typography></Box><Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: .7, direction: 'ltr' }}><MiniStat label="SENSORS" value="12 online" accent/><MiniStat label="LAST UPDATE" value="38 sec"/></Box><GlassPlate sx={{ p: .8, minHeight: 0, direction: 'ltr' }}>{[['Temperature', '24.8 °C', C.success], ['Humidity', '46%', C.success], ['CO₂', '742 ppm', C.warning]].map(([name, val, color], i) => <Box key={String(name)} sx={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 1, alignItems: 'center', py: .55, borderBottom: i < 2 ? '1px solid rgba(255,255,255,.07)' : 'none' }}><Box sx={{ display: 'flex', alignItems: 'center', gap: .55 }}><Box sx={{ width: 5, height: 5, borderRadius: '50%', bgcolor: color }}/><Typography sx={{ fontSize: 10.5, fontWeight: 700 }}>{name}</Typography></Box><Typography sx={{ fontSize: 10.5, fontWeight: 800, color: C.muted }}>{val}</Typography></Box>)}</GlassPlate></Box>; }
function GlassImage({ size }: Props) { const p = profile(size); return <Box sx={{ height: '100%', minHeight: 0, borderRadius: '14px', position: 'relative', overflow: 'hidden', background: 'linear-gradient(135deg,#07101f,#1b2740 48%,#31415c)', border: '1px solid rgba(255,255,255,.13)' }}><Box sx={{ position: 'absolute', inset: 0, background: 'radial-gradient(circle at 72% 26%,rgba(255,255,255,.28),transparent 18%),linear-gradient(180deg,transparent 55%,rgba(2,8,23,.62))' }}/><Box sx={{ position: 'absolute', left: '13%', right: '13%', bottom: '13%', height: p.large ? '54%' : '44%', border: '1px solid rgba(255,255,255,.30)', borderRadius: '52% 52% 12% 12%', boxShadow: 'inset 0 0 30px rgba(125,211,252,.05)' }}/><Box sx={{ position: 'absolute', left: 9, top: 9 }}><StatusText color={C.danger}>REC · LIVE</StatusText></Box><Box sx={{ position: 'absolute', left: 10, bottom: 9, right: 10, display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: 9.5, color: '#fff', fontWeight: 700 }}>Camera 04 · 09:44:12</Typography>{p.large && <Typography sx={{ fontSize: 9, color: C.muted }}>1920×1080 · 18 fps</Typography>}</Box></Box>; }
function GlassIframe({ locale, size }: Props) { const p = profile(size); return <Box sx={{ height: '100%', border: '1px solid rgba(255,255,255,.13)', borderRadius: '14px', overflow: 'hidden', background: 'rgba(3,13,29,.25)', display: 'grid', gridTemplateRows: '28px 1fr' }}><Box sx={{ px: .8, display: 'flex', alignItems: 'center', gap: .45, borderBottom: '1px solid rgba(255,255,255,.08)', background: 'rgba(255,255,255,.035)' }}>{[C.danger, C.warning, C.success].map(c => <Box key={c} sx={{ width: 6, height: 6, borderRadius: '50%', bgcolor: c }}/>)}{p.large && <Typography sx={{ ml: .6, fontSize: 8.5, color: C.faint, direction: 'ltr' }}>embedded-app.local/ops</Typography>}</Box>{!p.large ? <Box sx={{ display: 'grid', placeItems: 'center', textAlign: 'center', px: 2 }}><Box><Typography sx={{ fontSize: 14, fontWeight: 820 }}>{tr(locale, 'External content', 'محتوای خارجی')}</Typography><Typography sx={{ mt: .35, fontSize: 9.5, color: C.muted }}>iframe / HTML canvas / app</Typography></Box></Box> : <Box sx={{ minHeight: 0, display: 'grid', gridTemplateColumns: '72px 1fr', direction: 'ltr' }}><Box sx={{ borderRight: '1px solid rgba(255,255,255,.07)', p: .7, display: 'grid', alignContent: 'start', gap: .45 }}>{['Overview', 'Devices', 'Rules', 'Logs'].map((x, i) => <Box key={x} sx={{ px: .6, py: .5, borderRadius: '7px', fontSize: 8.5, fontWeight: i === 0 ? 800 : 650, color: i === 0 ? C.blue : C.muted, background: i === 0 ? 'rgba(125,211,252,.08)' : 'transparent' }}>{x}</Box>)}</Box><Box sx={{ p: .8, minWidth: 0, display: 'grid', gridTemplateRows: 'auto auto minmax(0,1fr)', gap: .7 }}><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Typography sx={{ fontSize: 11, fontWeight: 820 }}>{tr(locale, 'Embedded operations', 'نمای عملیاتی')}</Typography><StatusText>LIVE</StatusText></Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: .55 }}><MiniStat label="ONLINE" value="18" accent/><MiniStat label="ALARMS" value="2"/><MiniStat label="LATENCY" value="84 ms"/></Box><GlassPlate sx={{ p: .6, minHeight: 0 }}><LuminousChart values={[32, 38, 35, 48, 51, 46, 58, 62, 60, 72, 68, 76]} color={C.blue} fill/></GlassPlate></Box></Box>}</Box>; }
function GlassScada({ locale, size }: Props) { const p = profile(size); return <Box sx={{ height: '100%', display: 'grid', gridTemplateRows: p.large ? 'minmax(0,1fr) auto' : '1fr', gap: .8, direction: 'ltr' }}><GlassPlate sx={{ minHeight: 0, p: .4, position: 'relative', overflow: 'hidden' }}><svg viewBox="0 0 560 220" width="100%" height="100%" preserveAspectRatio="xMidYMid meet"><defs><marker id="glass-flow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z" fill={C.blue}/></marker></defs><rect x="20" y="48" width="126" height="128" rx="14" fill="rgba(125,211,252,.06)" stroke="rgba(255,255,255,.14)"/><rect x="29" y="104" width="108" height="63" rx="9" fill="rgba(34,211,238,.25)"/><path d="M29 104 Q56 96 83 104 T137 104" fill="none" stroke={C.blue} strokeWidth="2"/><text x="83" y="88" textAnchor="middle" fill="#f7fbff" fontSize="14" fontWeight="700">TANK 01</text><text x="83" y="130" textAnchor="middle" fill="#e8fbff" fontSize="26" fontWeight="800">63%</text><line x1="146" y1="112" x2="220" y2="112" stroke="rgba(231,245,249,.45)" strokeWidth="6"/><line x1="163" y1="112" x2="210" y2="112" stroke={C.blue} strokeWidth="2" markerEnd="url(#glass-flow)"/><circle cx="260" cy="112" r="36" fill="rgba(196,181,253,.08)" stroke={C.violet} strokeWidth="2"/><circle cx="260" cy="112" r="25" fill="rgba(255,255,255,.025)" stroke="rgba(255,255,255,.12)"/><text x="260" y="108" textAnchor="middle" fill="#f7fbff" fontSize="13" fontWeight="800">PUMP</text><text x="260" y="128" textAnchor="middle" fill={C.success} fontSize="10" fontWeight="800">RUNNING</text><line x1="296" y1="112" x2="380" y2="112" stroke="rgba(231,245,249,.45)" strokeWidth="6"/><line x1="315" y1="112" x2="368" y2="112" stroke={C.blue} strokeWidth="2" markerEnd="url(#glass-flow)"/><rect x="380" y="66" width="154" height="94" rx="14" fill="rgba(125,211,252,.05)" stroke="rgba(255,255,255,.14)"/><text x="457" y="104" textAnchor="middle" fill="#f7fbff" fontSize="14" fontWeight="700">VALVE V-02</text><text x="457" y="132" textAnchor="middle" fill={C.blue} fontSize="14" fontWeight="800">OPEN · 82%</text><text x="184" y="84" textAnchor="middle" fill="rgba(226,241,247,.58)" fontSize="10">18.4 L/min</text><text x="338" y="84" textAnchor="middle" fill="rgba(226,241,247,.58)" fontSize="10">2.6 bar</text></svg></GlassPlate>{p.large && <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: .65 }}><MiniStat label="FLOW" value="18.4 L/min" accent/><MiniStat label="PRESSURE" value="2.6 bar"/><MiniStat label="PUMP" value="1.82 A"/><MiniStat label="VALVE" value={tr(locale, 'OPEN', 'باز')}/></Box>}</Box>; }
export function GlassVisualRenderer(props: Props) { const v = props.def.visual; if (v === 'metric')
    return <GlassMetric {...props}/>; if (v === 'battery')
    return <GlassBattery {...props}/>; if (v === 'signal')
    return <GlassSignal {...props}/>; if (v === 'tank')
    return <GlassTank {...props}/>; if (v === 'boolean')
    return <GlassBoolean {...props}/>; if (v === 'alarm-indicator')
    return <GlassAlarm {...props}/>; if (v === 'gauge')
    return <GlassGauge {...props}/>; if (v === 'line' || v === 'area')
    return <GlassLine {...props}/>; if (v === 'bar')
    return <GlassBar {...props}/>; if (v === 'histogram')
    return <GlassHistogram {...props}/>; if (v === 'donut')
    return <GlassDonut {...props}/>; if (v === 'heatmap')
    return <GlassHeatmap {...props}/>; if (v === 'timeline')
    return <GlassTimeline {...props}/>; if (v === 'map' || v === 'route')
    return <GlassMap {...props}/>; if (v === 'coordinates')
    return <GlassCoordinates {...props}/>; if (v === 'compass')
    return <GlassCompass {...props}/>; if (v === 'button')
    return <GlassButton {...props}/>; if (v === 'switch')
    return <GlassSwitch {...props}/>; if (v === 'slider')
    return <GlassSlider {...props}/>; if (v === 'input')
    return <GlassInput {...props}/>; if (v === 'thermostat')
    return <GlassThermostat {...props}/>; if (v === 'color')
    return <GlassColor {...props}/>; if (v === 'direction')
    return <GlassDirection {...props}/>; if (v === 'table' || v === 'measurement-list' || v === 'alarms' || v === 'events' || v === 'logs')
    return <GlassTable {...props} mode={v}/>; if (v === 'clock')
    return <GlassClock {...props}/>; if (v === 'text')
    return <GlassText {...props}/>; if (v === 'image')
    return <GlassImage {...props}/>; if (v === 'iframe')
    return <GlassIframe {...props}/>; if (v === 'scada')
    return <GlassScada {...props}/>; return <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', color: C.muted }}><Typography sx={{ fontSize: 11 }}>Unsupported glass visual: {v}</Typography></Box>; }

